/* 马来西亚OSINT — 纯 Kotlin 多语言系统 */
package com.osint.malaysia.util

import androidx.compose.runtime.*

enum class AppLanguage(val code: String) {
    EN("en"), MS("ms"), ZH("zh");
    companion object { fun fromCode(code: String) = entries.find { it.code == code } ?: ZH }
}

data class UiStrings(
    val appName: String, val appTagline: String,
    val navHome: String, val navId: String, val navCompany: String,
    val navSocial: String, val navCourt: String, val navSettings: String,
    val homeTitle: String, val homeSubtitle: String,
    val homeHint: String, val homeRefresh: String,
    val homeBnmTitle: String, val homeBnmEmpty: String,
    val idTitle: String, val idSubtitle: String, val idHint: String, val idBtn: String,
    val idMykad: String, val idMykadFail: String, val idSspi: String,
    val idWanted: String, val idSprm: String,
    val coSsmtab: String, val coYptab: String,
    val coSsmTitle: String, val coSsmSub: String, val coSsmHint: String, val coSsmBtn: String,
    val coSsmResult: String, val coYpTitle: String, val coYpSub: String,
    val coYpHint: String, val coYpBtn: String, val coInfo: String, val coNotFound: String,
    val soTitle: String, val soSub: String, val soHint: String, val soBtn: String,
    val soGuide: String, val soGuide1: String, val soGuide2: String, val soGuide3: String,
    val soEmpty: String, val soNone: String, val soSearching: (Int) -> String, val soFound: (Int) -> String,
    val ctTitle: String, val ctSub: String, val ctHint: String, val ctBtn: String,
    val ctResult: String, val ctNoResult: String, val ctRaw: String, val ctPdf: String,
    val setAppear: String, val setAuto: String, val setAutoD: String,
    val setLight: String, val setLightD: String, val setDark: String, val setDarkD: String,
    val setLang: String, val setLangEn: String, val setLangMs: String, val setLangZh: String,
    val setTrans: String, val setTransD: String, val setAbout: String,
    val aboutApp: String, val aboutVer: String, val aboutAuthor: String,
    val aboutEmail: String, val aboutRepo: String,
    val aboutBestTitle: String, val aboutBestDesc: String, val aboutDisc: String,
    val loading: String, val noData: String, val networkError: String, val generalError: String,
    val btnSearch: String, val btnClear: String,
    val lbRegNo: String, val lbEntityCode: String, val lbEntityType: String,
    val lbBirthday: String, val lbProvince: String, val lbId: String,
    val lbCompany: String, val lbCategory: String, val lbAddress: String,
    val lbWebsite: String, val lbSource: String, val lbCaseNo: String,
    val lbCharge: String, val lbSentence: String, val lbLaw: String,
    val lbJudge: String, val lbCorum: String, val lbParties: String,
    val lbAppeal: String, val lbJudgment: String, val lbCaseId: String,
    val lbFiles: String, val lbRecord: String,
    val statMatch: String, val statFields: String, val statSource: String,
    val statTotal: String, val statPage: String,
    val riskHigh: String, val riskHighD: String,
    val riskMed: String, val riskMedD: String,
    val riskClean: String, val riskCleanD: String,
    val riskNoData: String, val riskPdrm: String,
)

private val ZH_STRINGS = UiStrings(
    appName = "马来西亚OSINT", appTagline = "开源情报工具",
    navHome = "首页", navId = "身份证", navCompany = "企业",
    navSocial = "社交", navCourt = "法庭", navSettings = "设置",
    homeTitle = "反诈骗查询", homeSubtitle = "PDRM Semak Mule — 查询电话/银行账号是否涉诈",
    homeHint = "输入电话号码或银行账号", homeRefresh = "刷新警示",
    homeBnmTitle = "国行消费者警示名单", homeBnmEmpty = "暂无警示记录",
    idTitle = "身份证综合查询", idSubtitle = "SSPI移民局 + MyKad解析 + 通缉名单 + 反贪会",
    idHint = "输入12位身份证号码 (如 990101075678)", idBtn = "综合查询",
    idMykad = "MyKad 身份证解析", idMykadFail = "无法解析，请检查输入",
    idSspi = "SSPI 移民局状态", idWanted = "通缉名单匹配", idSprm = "反贪会腐败记录",
    coSsmtab = "SSM注册号", coYptab = "企业黄页",
    coSsmTitle = "SSM 注册号解析", coSsmSub = "解析马来西亚公司委员会(SSM)注册号",
    coSsmHint = "输入SSM注册号 (如 123456-01-7890)", coSsmBtn = "解析",
    coSsmResult = "解析结果", coYpTitle = "企业黄页搜索",
    coYpSub = "搜索马来西亚黄页(MalaysiaYP)，联动反诈骗数据库",
    coYpHint = "输入企业名称关键词", coYpBtn = "企业查询",
    coInfo = "企业信息", coNotFound = "未找到匹配企业",
    soTitle = "社交媒体足迹搜索", soSub = "跨平台用户名枚举 — 遍历60+社交平台",
    soHint = "输入要搜索的用户名", soBtn = "开始搜索",
    soGuide = "使用说明", soGuide1 = "输入用户名，系统自动遍历各大社交平台",
    soGuide2 = "搜索结果实时显示，无需等待",
    soGuide3 = "支持全球主流社交平台、开发者社区、论坛等",
    soEmpty = "该用户名未在任何平台发现", soNone = "未发现匹配平台",
    soSearching = { "正在搜索... 已找到 $it 个平台" },
    soFound = { "发现匹配 - $it 个平台" },
    ctTitle = "电子法庭查询", ctSub = "搜索马来西亚联邦法院电子判决 - e-Judgment Portal",
    ctHint = "输入姓名或案件关键词", ctBtn = "法庭搜索",
    ctResult = "搜索结果", ctNoResult = "未找到相关法庭记录",
    ctRaw = "API原始响应（解析失败）", ctPdf = "点击查看判决书PDF",
    setAppear = "外观设置", setAuto = "跟随系统", setAutoD = "自动匹配浅色/深色模式",
    setLight = "浅色模式", setLightD = "始终使用浅色主题",
    setDark = "深色模式", setDarkD = "始终使用深色主题",
    setLang = "语言设置", setLangEn = "English", setLangMs = "Bahasa Melayu", setLangZh = "中文",
    setTrans = "内容翻译", setTransD = "将API返回的马来文/英文翻译为中文",
    setAbout = "关于",
    aboutApp = "马来西亚OSINT", aboutVer = "版本 1.0.0",
    aboutAuthor = "作者：哪吒网络安全的钟智强",
    aboutEmail = "johnmelodymel@qq.com",
    aboutRepo = "gitcode.com/ctkqiang_sr/MalaysianOSINTAPP",
    aboutBestTitle = "我已经尽力了！",
    aboutBestDesc = "这个 App 是我一个人用热情和心血打造的。虽然我已经尽了最大努力保证准确性和可靠性，但难免还有 Bug 和需要改进的地方。欢迎提供反馈和贡献代码 - 一起为全马来西亚人打造好用的 OSINT 工具！",
    aboutDisc = "本应用仅供安全研究与合法授权测试使用。使用者应遵守马来西亚相关法律法规，对自身行为负责。",
    loading = "查询中...", noData = "暂无数据",
    networkError = "网络连接失败", generalError = "查询出错，请重试",
    btnSearch = "查询", btnClear = "清除",
    lbRegNo = "注册号", lbEntityCode = "实体代码", lbEntityType = "实体类型",
    lbBirthday = "出生日期", lbProvince = "州属/直辖区", lbId = "唯一标识符",
    lbCompany = "企业名称", lbCategory = "行业类别", lbAddress = "地址",
    lbWebsite = "网站", lbSource = "数据来源", lbCaseNo = "案件编号",
    lbCharge = "罪名", lbSentence = "判决", lbLaw = "适用法律",
    lbJudge = "法官", lbCorum = "合议庭", lbParties = "当事人",
    lbAppeal = "上诉日期", lbJudgment = "判决日期", lbCaseId = "案件ID",
    lbFiles = "文件", lbRecord = "记录",
    statMatch = "匹配记录", statFields = "数据字段", statSource = "数据来源",
    statTotal = "总记录数", statPage = "当前页",
    riskHigh = "存在记录", riskHighD = "该号码/账号在PDRM数据库中有多条记录，请注意核实",
    riskMed = "需核实", riskMedD = "该号码/账号在PDRM数据库中有记录，请查看详情",
    riskClean = "未发现记录", riskCleanD = "PDRM Semak Mule 数据库中未查询到相关记录",
    riskNoData = "此号码/账号未在PDRM诈骗数据库中登记",
    riskPdrm = "PDRM",
)

// ZH about strings for all languages
private val ZH_ABOUT = listOf(
    "马来西亚OSINT", "版本 1.0.0",
    "作者：哪吒网络安全的钟智强",
    "johnmelodymel@qq.com",
    "gitcode.com/ctkqiang_sr/MalaysianOSINTAPP",
    "我已经尽力了！",
    "这个 App 是我一个人用热情和心血打造的。虽然我已经尽了最大努力保证准确性和可靠性，但难免还有 Bug 和需要改进的地方。欢迎提供反馈和贡献代码 - 一起为全马来西亚人打造好用的 OSINT 工具！",
    "本应用仅供安全研究与合法授权测试使用。使用者应遵守马来西亚相关法律法规，对自身行为负责。",
)

private val EN_STRINGS = UiStrings(
    appName = "MalaysianOSINT", appTagline = "Open-Source Intelligence",
    navHome = "Home", navId = "IC Check", navCompany = "Company",
    navSocial = "Social", navCourt = "Court", navSettings = "Settings",
    homeTitle = "Anti-Scam Search", homeSubtitle = "PDRM Semak Mule - Check phone/bank account for scam links",
    homeHint = "Enter phone number or bank account", homeRefresh = "Refresh Alerts",
    homeBnmTitle = "BNM Consumer Alert List", homeBnmEmpty = "No active alerts",
    idTitle = "Comprehensive IC Search", idSubtitle = "SSPI Immigration + MyKad Parsing + Wanted List + MACC",
    idHint = "Enter 12-digit IC (e.g. 990101075678)", idBtn = "Search All",
    idMykad = "MyKad IC Parsing", idMykadFail = "Unable to parse, check input",
    idSspi = "SSPI Immigration Status", idWanted = "Wanted List Matches", idSprm = "MACC Corruption Records",
    coSsmtab = "SSM Reg. No.", coYptab = "Yellow Pages",
    coSsmTitle = "SSM Registration Parser", coSsmSub = "Parse SSM (Companies Commission) registration numbers",
    coSsmHint = "Enter SSM reg. no. (e.g. 123456-01-7890)", coSsmBtn = "Parse",
    coSsmResult = "Parsing Result", coYpTitle = "Company Directory",
    coYpSub = "Search Malaysia Yellow Pages, linked with anti-scam database",
    coYpHint = "Enter company keyword", coYpBtn = "Search",
    coInfo = "Company Info", coNotFound = "No matching company found",
    soTitle = "Social Media Footprint", soSub = "Cross-platform username enumeration - 60+ platforms",
    soHint = "Enter username", soBtn = "Start Search",
    soGuide = "Guide", soGuide1 = "Enter target username - system scans all major social platforms",
    soGuide2 = "Results display in real-time, no need to wait",
    soGuide3 = "Supports global social platforms, dev communities, forums",
    soEmpty = "Username not found on any platform", soNone = "No matching platforms found",
    soSearching = { "Searching... $it platforms found" },
    soFound = { "Matches - $it platforms" },
    ctTitle = "e-Court Search", ctSub = "Search Malaysian Federal Court e-Judgments",
    ctHint = "Enter name or case keyword", ctBtn = "Search Court",
    ctResult = "Search Results", ctNoResult = "No court records found",
    ctRaw = "API Raw Response (Parse Failed)", ctPdf = "Tap to view judgment PDF",
    setAppear = "Appearance", setAuto = "Follow System", setAutoD = "Match system light/dark mode",
    setLight = "Light Mode", setLightD = "Always use light theme",
    setDark = "Dark Mode", setDarkD = "Always use dark theme",
    setLang = "Language", setLangEn = "English", setLangMs = "Bahasa Melayu", setLangZh = "中文",
    setTrans = "Content Translation", setTransD = "Translate Malay/English API content to Chinese",
    setAbout = "About",
    aboutApp = ZH_ABOUT[0], aboutVer = ZH_ABOUT[1],
    aboutAuthor = ZH_ABOUT[2], aboutEmail = ZH_ABOUT[3], aboutRepo = ZH_ABOUT[4],
    aboutBestTitle = ZH_ABOUT[5], aboutBestDesc = ZH_ABOUT[6], aboutDisc = ZH_ABOUT[7],
    loading = "Loading...", noData = "No data",
    networkError = "Network error", generalError = "Error, try again",
    btnSearch = "Search", btnClear = "Clear",
    lbRegNo = "Reg. No.", lbEntityCode = "Entity Code", lbEntityType = "Entity Type",
    lbBirthday = "Date of Birth", lbProvince = "State/Territory", lbId = "Unique ID",
    lbCompany = "Company Name", lbCategory = "Category", lbAddress = "Address",
    lbWebsite = "Website", lbSource = "Source", lbCaseNo = "Case No.",
    lbCharge = "Charge", lbSentence = "Sentence", lbLaw = "Applicable Law",
    lbJudge = "Judge", lbCorum = "Panel", lbParties = "Parties",
    lbAppeal = "Appeal Date", lbJudgment = "Judgment Date", lbCaseId = "Case ID",
    lbFiles = "Files", lbRecord = "Record",
    statMatch = "Matches", statFields = "Fields", statSource = "Source",
    statTotal = "Total Records", statPage = "Page",
    riskHigh = "Records Found", riskHighD = "Multiple records in PDRM database - verify",
    riskMed = "Verification Needed", riskMedD = "Records found in PDRM database - check details",
    riskClean = "No Records", riskCleanD = "Not found in PDRM Semak Mule database",
    riskNoData = "Not registered in PDRM scam database",
    riskPdrm = "PDRM",
)

private val MS_STRINGS = UiStrings(
    appName = "MalaysianOSINT", appTagline = "Risikan Sumber Terbuka",
    navHome = "Utama", navId = "IC", navCompany = "Syarikat",
    navSocial = "Sosial", navCourt = "Mahkamah", navSettings = "Tetapan",
    homeTitle = "Carian Anti-Penipuan", homeSubtitle = "PDRM Semak Mule - Semak telefon/akaun bank untuk penipuan",
    homeHint = "Masukkan nombor telefon atau akaun bank", homeRefresh = "Segar Semula",
    homeBnmTitle = "Senarai Amaran Pengguna BNM", homeBnmEmpty = "Tiada amaran",
    idTitle = "Carian IC Komprehensif", idSubtitle = "SSPI Imigresen + MyKad + Dikehendaki + SPRM",
    idHint = "Masukkan IC 12 digit (cth. 990101075678)", idBtn = "Cari Semua",
    idMykad = "Penghuraian MyKad", idMykadFail = "Tidak dapat hurai, semak input",
    idSspi = "Status Imigresen SSPI", idWanted = "Padanan Dikehendaki", idSprm = "Rekod Rasuah SPRM",
    coSsmtab = "No. SSM", coYptab = "Halaman Kuning",
    coSsmTitle = "Penghurai Pendaftaran SSM", coSsmSub = "Hurai nombor pendaftaran SSM",
    coSsmHint = "Masukkan no. SSM (cth. 123456-01-7890)", coSsmBtn = "Hurai",
    coSsmResult = "Hasil Penghuraian", coYpTitle = "Direktori Syarikat",
    coYpSub = "Cari Halaman Kuning Malaysia, dikaitkan pangkalan data anti-penipuan",
    coYpHint = "Masukkan kata kunci syarikat", coYpBtn = "Cari",
    coInfo = "Maklumat Syarikat", coNotFound = "Tiada syarikat dijumpai",
    soTitle = "Jejak Media Sosial", soSub = "Penghitungan nama pengguna - 60+ platform",
    soHint = "Masukkan nama pengguna", soBtn = "Mula Carian",
    soGuide = "Panduan", soGuide1 = "Masukkan nama pengguna - sistem imbas platform sosial",
    soGuide2 = "Keputusan dipaparkan masa nyata",
    soGuide3 = "Menyokong platform global, komuniti pembangun, forum",
    soEmpty = "Nama pengguna tidak dijumpai", soNone = "Tiada platform sepadan",
    soSearching = { "Mencari... $it platform ditemui" },
    soFound = { "Padanan - $it platform" },
    ctTitle = "Carian e-Mahkamah", ctSub = "Cari e-Penghakiman Mahkamah Persekutuan Malaysia",
    ctHint = "Masukkan nama atau kata kunci kes", ctBtn = "Cari Mahkamah",
    ctResult = "Hasil Carian", ctNoResult = "Tiada rekod mahkamah",
    ctRaw = "Respons Mentah API", ctPdf = "Ketik untuk lihat PDF",
    setAppear = "Penampilan", setAuto = "Ikut Sistem", setAutoD = "Padan mod gelap/cerah sistem",
    setLight = "Mod Cerah", setLightD = "Sentiasa guna tema cerah",
    setDark = "Mod Gelap", setDarkD = "Sentiasa guna tema gelap",
    setLang = "Bahasa", setLangEn = "English", setLangMs = "Bahasa Melayu", setLangZh = "中文",
    setTrans = "Terjemahan", setTransD = "Terjemah kandungan API ke Bahasa Cina",
    setAbout = "Perihal",
    aboutApp = ZH_ABOUT[0], aboutVer = ZH_ABOUT[1],
    aboutAuthor = ZH_ABOUT[2], aboutEmail = ZH_ABOUT[3], aboutRepo = ZH_ABOUT[4],
    aboutBestTitle = ZH_ABOUT[5], aboutBestDesc = ZH_ABOUT[6], aboutDisc = ZH_ABOUT[7],
    loading = "Memuatkan...", noData = "Tiada data",
    networkError = "Ralat rangkaian", generalError = "Ralat, cuba lagi",
    btnSearch = "Cari", btnClear = "Kosongkan",
    lbRegNo = "No. Pendaftaran", lbEntityCode = "Kod Entiti", lbEntityType = "Jenis Entiti",
    lbBirthday = "Tarikh Lahir", lbProvince = "Negeri/Wilayah", lbId = "ID Unik",
    lbCompany = "Nama Syarikat", lbCategory = "Kategori", lbAddress = "Alamat",
    lbWebsite = "Laman Web", lbSource = "Sumber", lbCaseNo = "No. Kes",
    lbCharge = "Pertuduhan", lbSentence = "Hukuman", lbLaw = "Undang-Undang",
    lbJudge = "Hakim", lbCorum = "Panel", lbParties = "Pihak",
    lbAppeal = "Tarikh Rayuan", lbJudgment = "Tarikh Penghakiman", lbCaseId = "ID Kes",
    lbFiles = "Fail", lbRecord = "Rekod",
    statMatch = "Padanan", statFields = "Medan", statSource = "Sumber",
    statTotal = "Jumlah Rekod", statPage = "Halaman",
    riskHigh = "Rekod Ditemui", riskHighD = "Pelbagai rekod dalam pangkalan data PDRM - sahkan",
    riskMed = "Pengesahan Diperlukan", riskMedD = "Rekod ditemui dalam PDRM - semak",
    riskClean = "Tiada Rekod", riskCleanD = "Tidak ditemui dalam PDRM Semak Mule",
    riskNoData = "Tidak berdaftar dalam pangkalan data penipuan PDRM",
    riskPdrm = "PDRM",
)

private val STRINGS_MAP = mapOf(AppLanguage.ZH to ZH_STRINGS, AppLanguage.EN to EN_STRINGS, AppLanguage.MS to MS_STRINGS)
val LocalStrings = staticCompositionLocalOf { ZH_STRINGS }
fun stringsFor(lang: AppLanguage): UiStrings = STRINGS_MAP[lang] ?: ZH_STRINGS
